export var books = [
  {
    id: 1,
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J.K. Rowling',
    publisher: 'Arthur A. Levine Books',
    isbn: '978-0439358064',
    pages: 896,
    coverImg: 'img base 64',
    borrowed: false,
    loanTo: '',
  },
  {
    id: 2,
    title: 'The Fellowship of the Ring',
    author: 'J.R.R Tolkien',
    publisher: 'George Allen & Unwin',
    isbn: '12228601',
    pages: 423,
    coverImg: 'img base 64',
    borrowed: false,
    loanTo: '',
  },
  {
    id: 3,
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J.K. Rowling',
    publisher: ' Arthur A. Levine Books',
    isbn: '978-0439358064',
    pages: 896,
    coverImg: 'img base 64',
    borrowed: false,
    loanTo: '',
  },
  {
    id: 4,
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J.K. Rowling',
    publisher: ' Arthur A. Levine Books',
    isbn: '978-0439358064',
    pages: 896,
    coverImg: 'img base 64',
    borrowed: true,
    loanTo: '',
  },
  {
    id: 5,
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J.K. Rowling',
    publisher: ' Arthur A. Levine Books',
    isbn: '978-0439358064',
    pages: 896,
    coverImg: 'img base 64',
    borrowed: false,
    loanTo: '',
  },
];
